[package]
name = "await-openai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tiktoken-rs = { version = "0", optional = true }
anyhow = { version = "1", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
async-openai = "0"

[features]
default = ["chat-completion"]
chat-completion = []
tiktoken = ["tiktoken-rs", "anyhow"]

[[bench]]
name = "async-openai"
harness = false
