[package]
name = "await-openai"
description = "utils for openai"
version = "0.3.0"
edition = "2021"
readme = "README.md"
keywords = ["openai"]
license-file = "LICENSE"
homepage = "https://github.com/washanhanzi/await-openai"
repository = "https://github.com/washanhanzi/await-openai"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiktoken-rs = { version = "0", optional = true }
anyhow = { version = "1", optional = true }
schemars = { version = "0.8", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
async-openai = "0"
openai-func-enums = "0"

[features]
default = []
tiktoken = ["tiktoken-rs", "anyhow"]
tools = ["schemars", "anyhow"]

[[bench]]
name = "async-openai"
harness = false
